### ISSUE TITLE
Check zlib feature error

### ISSUE THREAD

**Issue by aguaiyoung** [libbpf/bpftool#3]
Makefile.feature may check  requirement lib like as zlib,but if clang's version 11.0.0 it's not work well.
some code need escape character like `\n` you need add like that:
```diff
-        $(shell echo $(ZLIB_PROBE) | \
+        $(shell echo -e $(ZLIB_PROBE) | \
       $(CC) $(CFLAGS) -Wall -Werror $(LDFLAGS) -x c - -lz -S -o - >/dev/null 2>&1 \
     && echo 1)
```
or it output error like that:
```
<stdin>:1:18: error: extra tokens at end of #include directive [-Werror,-Wextra-tokens]
#include <zlib.h>\n int main(void) {  z_stream zs;      inflateInit(&zs);       return 0; }
                 ^
                 //
1 error generated.
```
 and other `echo` need `echo -e` replace

Makefile.include need add EXTRA_WARNINGS in clang version is 11.0.0
```
      +        -Wno-unused-command-line-argument \
```

**Comment by qmonnet** [comment]
Hi, thanks a lot for the report!

Both issues are bugs in the feature detection. It looks that `clang` does not need the flags telling to the linker what libraries to use, and this results in warnings that break detection due to the use of `-Werror`. Adding `Wno-unused-command-line-argument` seems to fix it indeed.

I don't directly experience the issue with the `echo` on my setup, it “works fine for me”. But `echo` is not known to be portable, and I'm ready to believe that the current code breaks on other environments. I observed that the `$(shell echo)` invocation calls `/bin/sh` (`dash` for me) which is supposed to use `/usr/bin/echo`, but it seems that in some cases (including the default case for me, where the current code works), some built-in `echo` is used instead. I think it's some built-in from make, but didn't manage to confirm it. Anyway. Adding `-e` is not a solution though: it breaks on my setup. I think we'll switch to using `printf` instead of `echo`, hopefully it will be more stable.

If you have a moment, could you please check whether the changes in #5 fix the build on your setup?

**Comment by aguaiyoung** [comment]
> Hi, thanks a lot for the report!
> 
> Both issues are bugs in the feature detection. It looks that `clang` does not need the flags telling to the linker what libraries to use, and this results in warnings that break detection due to the use of `-Werror`. Adding `Wno-unused-command-line-argument` seems to fix it indeed.
> 
> I don't directly experience the issue with the `echo` on my setup, it “works fine for me”. But `echo` is not known to be portable, and I'm ready to believe that the current code breaks on other environments. I observed that the `$(shell echo)` invocation calls `/bin/sh` (`dash` for me) which is supposed to use `/usr/bin/echo`, but it seems that in some cases (including the default case for me, where the current code works), some built-in `echo` is used instead. I think it's some built-in from make, but didn't manage to confirm it. Anyway. Adding `-e` is not a solution though: it breaks on my setup. I think we'll switch to using `printf` instead of `echo`, hopefully it will be more stable.
> 
> If you have a moment, could you please check whether the changes in #5 fix the build on your setup?

printf is still error in my enviroment, centos 7.6 

<stdin>:1:18: error: extra tokens at end of #include directive [-Werror,-Wextra-tokens]
#include <zlib.h>\n int main(void) {  z_stream zs;      inflateInit(&zs);       return 0; }

if in my terminal,like that it's ok:
  [yangg@centos7_6 src]$ printf '%b\n' 'test\n'
test

[aguai@centos7_6 src]$ printf '%b\n' 'test'
test
[aguai@centos7_6 src]$ printf '%b' 'test'
test[aguai@centos7_6 src]$

**Comment by aguaiyoung** [comment]
> Hi, thanks a lot for the report!
> 
> Both issues are bugs in the feature detection. It looks that `clang` does not need the flags telling to the linker what libraries to use, and this results in warnings that break detection due to the use of `-Werror`. Adding `Wno-unused-command-line-argument` seems to fix it indeed.
> 
> I don't directly experience the issue with the `echo` on my setup, it “works fine for me”. But `echo` is not known to be portable, and I'm ready to believe that the current code breaks on other environments. I observed that the `$(shell echo)` invocation calls `/bin/sh` (`dash` for me) which is supposed to use `/usr/bin/echo`, but it seems that in some cases (including the default case for me, where the current code works), some built-in `echo` is used instead. I think it's some built-in from make, but didn't manage to confirm it. Anyway. Adding `-e` is not a solution though: it breaks on my setup. I think we'll switch to using `printf` instead of `echo`, hopefully it will be more stable.
> 
> If you have a moment, could you please check whether the changes in #5 fix the build on your setup?

check in my env, it's ok.
thank your replay.
...                        libbfd: [ on  ]
...        disassembler-four-args: [ OFF ]
...                          zlib: [ on  ]
...                        libcap: [ OFF ]
...               clang-bpf-co-re: [ on  ]

**Comment by qmonnet** [comment]
And thank you for testing :) Merged now.
